# on dockerhub as ialarmedalien/sdkbase2_perl
FROM kbase/sdkbase2:latest

# install cpan dependencies and then remove installation leftovers
COPY ./cpanfile /kb/module/cpanfile

WORKDIR /kb/module

RUN cpanm --installdeps . \
    && cd ~ && rm -rf .cpanm
