FROM kbase/sdkbase2:latest

# install cpan dependencies and then remove installation leftovers
COPY ./cpanfile /kb/module/cpanfile

WORKDIR /kb/module

RUN cpanm --installdeps . \
    && cd ~ && rm -rf .cpanm

# update kb-sdk
RUN cd /root/src/kb_sdk \
    && git checkout develop \
    && make \
    && cp bin/kb-sdk /usr/local/bin

COPY ./ /kb/module

WORKDIR /kb/module

ENV APP_DIR /kb/module
ENV KB_DEPLOYMENT_CONFIG /kb/module/deploy.cfg
ENV PERL5LIB="/kb/module/lib:${PERL5LIB}"

RUN git clone https://github.com/kbase/relation_engine.git

RUN env && \
    mkdir -p /kb/module/work && \
    chmod -R a+rw /kb/module && \
    make all

ENTRYPOINT [ "./scripts/entrypoint.sh" ]

CMD [ ]
