FROM kbase/sdkbase2:latest

# update kb-sdk
RUN cd /root/src/kb_sdk \
    && git remote add iaa https://github.com/ialarmedalien/kb_sdk.git \
    && git pull iaa better_perl_and_tests \
    && git checkout better_perl_and_tests \
    && make \
    && cp bin/kb-sdk /usr/local/bin

WORKDIR /kb/module
COPY ./cpanfile /kb/module/cpanfile

# install cpan dependencies and then remove installation leftovers
RUN cpanm --installdeps . \
    && cd ~ && rm -rf .cpanm
