name: Docker Image CI

on:
  [push, pull_request]

jobs:

  install_kbsdk_and_test:
#    needs: push_to_dockerhub
    runs-on: ubuntu-latest
    steps:
    - name: checkout git repo
      uses: actions/checkout@v2

    - name: pull and run docker image
      shell: bash
      env:
        KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
        GITHUB_ACTIONS_CI: 1
      run: |
        make docker-test

#  push_to_dockerhub:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Build & Push to Docker Hub
#        uses: opspresso/action-docker@master
#        with:
#          args: --docker
#        env:
#          USERNAME: ${{ secrets.DOCKER_USERNAME }}
#          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#          IMAGE_NAME: "ialarmedalien/modernperl_base"
#          DOCKERFILE: "Dockerfile_perlbase"
#          TAG_NAME: "kb_cytoscape"
#          LATEST: "true"
